language: ruby
git:
    depth: 3
cache: bundler
bundler_args: --without development
script:
    - "bundle exec rake $CHECK"
notifications:
    email: false
rvm:
    - 2.4.0
env:
    - "CHECK=docs:verify"
    - "CHECK=test:rubocop"
    - "CHECK=test:flog"
    - "CHECK=test:flay"
    - "CHECK=test:spec"
